### ISSUE TITLE
Patching doesn't work on Windows

### ISSUE THREAD

**Issue by JeremyStepp** [JeremyStepp/OneLauncher#1]
Most of my issues are on my private project server for now, but I have no clue how to fix this one.
As far as I can tell, patching should %100 work, but it doesn't. It just instantly says finished and gives no output no matter what. The patch command is running with QProcess, and the problem seems to be there somehow. I can't seem to put anything in with arguments. Thanks to Luchs for reporting the issue.

**Comment by MeisterLuchs** [comment]
Tried it again with yesterday's game update and now it worked perfectly. But I'm still missing output other than "Finished", if I haven't monitored network traffic and folder changes I wouldn't know it's doing something at all.

**Comment by MeisterLuchs** [comment]
Ok Forget that. After yesterday's game update it won't patch correctly again.

**Comment by JeremyStepp** [comment]
Here is the example I have posted on forums for help. Unfortunantly I have not gotten any help though. (Probably because you need lotro to reproduce it):

I am trying to launch a patching dll for The Lord of The Rings Online with QProcess and get the output, but it only works on Linux (where I am doing it through wine with QProcess). I think it would be the same with any dll though. I just don't know of any standard ones I could use in an example.

I have tried a lot without success, and have come to the conclusion that the issue may be rundll32 launching the patcher as a separate process that is not tracked by QProcess. This doesn't even really hold up though, because the patching at least in my testing (others say it has worked sometimes) has not happened.


Example:
```
from qtpy import QtCore, QtWidgets
import sys

class PatchWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setFixedSize(720, 400)

        self.txtLog = QtWidgets.QTextBrowser(self)
        self.txtLog.setGeometry(5,5,710,351)

        self.process = QtCore.QProcess()
        self.process.readyReadStandardOutput.connect(self.readOutput)
        self.process.readyReadStandardError.connect(self.readErrors)
        self.process.finished.connect(self.processFinished)

        self.process.setWorkingDirectory("C:/LOTRO/")

        self.show()

        self.startProcess()

    def readOutput(self):
        line = self.process.readAllStandardOutput()
        line = str(line, encoding="utf8", errors="replace")
        self.txtLog.append(line)

    def readErrors(self):
        line = self.process.readAllStandardError()
        line = str(line, encoding="utf8", errors="replace")
        self.txtLog.append(line)

    def processFinished(self, exitCode, exitStatus):
        self.txtLog.append("Process Finished")

    def startProcess(self):
        self.process.start("rundll32", ["patchclient.dll,Patch", "patch.lotro.com:6015", 
                                      "--language DE", "--productcode LOTRO", "--highres"])
        self.txtLog.append("Process Started")

app = QtWidgets.QApplication(sys.argv)
PatchWindow = PatchWindow()

sys.exit(app.exec_())
```
There should be output similar to:
```
Connecting to patch.lotro.com:6015

Checking files...
files to patch: 0 bytes to download: 0
Patching files:

File patching complete
```
, but there is nothing. The actual code for this project is [here](https://github.com/JeremyStepp/OneLauncher/blob/master/OneLauncher/PatchWindow.py)

Any help is appreciated.

**Comment by JeremyStepp** [comment]
I have gotten to do some testing on the actual OS and it seems that rundll32 never provides any output on Windows.  I fixed a few smaller problems and added an indication of when patching is occurring, so it should work now; it just won't be as good an experience as on Linux and Mac. It is still possible that there could be a way to hook into the dll's output on Windows, but I'm not sure how. Maybe something fancy with ctypes. I'll re-open this if the issue's not truly solved everyone.

**Comment by JeremyStepp** [comment]
I recently found a log file for patchclient.dll and added it to the patching output on Windows. The feedback should be a lot closer to what you get on Linux and Mac now.
