### ISSUE TITLE
Cant launch the Launcher

### ISSUE THREAD

**Issue by iMonZ** [JeremyStepp/OneLauncher#10]
Hey I get this:

`Traceback (most recent call last):
  File "/Users/mvg/Downloads/OneLauncher/RunOneLauncher", line 30, in <module>
    import OneLauncher.Runner
  File "/Users/mvg/Downloads/OneLauncher/OneLauncher/Runner.py", line 29, in <module>
    from OneLauncher.MainWindow import MainWindow
  File "/Users/mvg/Downloads/OneLauncher/OneLauncher/MainWindow.py", line 32, in <module>
    import defusedxml.minidom
ModuleNotFoundError: No module named 'defusedxml'`

**Comment by JeremyStepp** [comment]
What operating system are you using and are you running it from source or the binary?

**Comment by JeremyStepp** [comment]
I took a closer look at your error message and it seems you're running from source. Make sure to install all the dependencies listed in the README [here](https://github.com/JeremyStepp/OneLauncher/blob/master/README.md#development-install). I'll go ahead and close this now. You can re-open it if this doesn't solve your issue.
