### ISSUE TITLE
Setup Fails to Launch Launcher

### ISSUE THREAD

**Issue by alexlarner** [JeremyStepp/OneLauncher#14]
Got this error when the setup (OneLauncher-1.2.3-linux-x64-installer.run) tried to run the launcher:

> There has been an error.
> Error running /home/alex/OneLauncher/build/OneLauncher : /bin/sh: 1: /home/alex/OneLauncher/build/OneLauncher: not found
> The application will exit now.

The file exists in the directory
![image](https://user-images.githubusercontent.com/77208751/104106455-03551380-5284-11eb-9709-950eac675e16.png)

I'm running:
OS: LMDE 4 Debbie
Kernel: 4.19.0-13-amd64
Wine: 4.0-2

How do I run the launcher?

**Comment by JeremyStepp** [comment]
Does the launcher on your Desktop or just directly running the OneLauncher executable in the build folder work?

**Comment by alexlarner** [comment]
Neither of those work. When I try to run the desktop launcher it just does nothing. When I try to run the OneLauncher executable I just get a Unknown file type error:

Here's the contents of the desktop launcher:
`[Desktop Entry]
Type=Application
Version=0.9.4
Name=OneLauncher
Comment=Run OneLauncher
Icon=/home/alex/OneLauncher/build/images/OneLauncherIcon.png
Exec=/home/alex/OneLauncher/build/OneLauncher
Terminal=false`

Here's the unknown file type error:
![image](https://user-images.githubusercontent.com/77208751/104243330-67b3d680-542e-11eb-9987-cab665092e42.png)

Is the OneLauncher file (~/OneLauncher/build/OneLauncher) supposed to have a file extension (i.e. .exe)?

**Comment by JeremyStepp** [comment]
Can you make sure the OneLauncher file has execution permissions? It should say in the permissions section of the file properties menu.

**Comment by alexlarner** [comment]
Yep, it has execute permissions:

![image](https://user-images.githubusercontent.com/77208751/104831306-8a425700-5855-11eb-83a8-0ade53c0097a.png)

**Comment by JeremyStepp** [comment]
I took a look at LMDE, and it seems like the issue is that its glibc is a lower version than the build requires.  You can check this on your computer by running `ldd OneLauncher` in the build folder. One of the reasons I was using GitHub Actions for the build was, so I could build it with an older glibc version. There have been some other issues with the GitHub Actions Linux build there, so the current Linux builds are done locally with my updated glibc version. I don't have time to fix those issues right now, so I'd suggest running it from source or building it yourself. It should be easy since its Python. The dependencies are listed in the  README.md file. You can install them with `pip3 install <requirement1> <requirement2>`  ect.

**Comment by alexlarner** [comment]
I installed the pre-reqs but I get errors when I try to run RunOneLauncher or try to build using setup.py:

> alex@windowsisgarbage:~/Downloads/OneLauncher-master$ python3 RunOneLauncher
> 
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
> 
> Aborted (core dumped)

Per [this](https://bugreports.qt.io/browse/QTBUG-88688), It appears to be an issue with Debian 10 (which LMDE 4 is directly based off of) and QT.

I created a symbolic link from libxcb-util.so.0.0.0 to libxcb-util.so.1.0.0, libxcb-util.so.1.0, and libxcb-util.so.1 per this [comment](https://forum.qt.io/topic/93247/qt-qpa-plugin-could-not-load-the-qt-platform-plugin-xcb-in-even-though-it-was-found/66) which allowed RunOneLauncher to run, but when it ran the items really overlapped each other:

![image](https://user-images.githubusercontent.com/77208751/106330676-a41a6b80-6251-11eb-9a35-6dc7346eae61.png)

The output of the Setup.py was really long so I attached it [here](https://github.com/JeremyStepp/OneLauncher/files/5896422/OneLauncher.Setup.py.Result.txt). It included some warnings like:

> WARNING: cannot find libxcb-util.so.1
> WARNING: cannot find libshiboken2.abi3.so.5.15

The setup.py created the build folder but I still don't know how I'm supposed to run the OneLauncher file in the newly created build folder/what I'm supposed to run it with. It has no file extension, and the file shows up as a file type of "application/x-sharedlib". Per [this](https://forum.qt.io/topic/84422/sharedlib-instead-of-executable-file-on-ubuntu), I'm guessing that the OneLauncher was created as a sharedlib instead of an executable because of a missing QT library.

![image](https://user-images.githubusercontent.com/77208751/106331502-0d4eae80-6253-11eb-9d13-d05735533082.png)

Sorry for all the back and forth on this, I'm rather new to Python and Linux. I'm a Windows System Engineer by trade, so I'm a lot more familiar with Windows & PowerShell, but I'm learning.

**Comment by JeremyStepp** [comment]
Sorry it's been a while. There wasn't much I could do since this isn't a problem with my software. I tested in a virtual machine, and it should work if you install the snapshots for shiboken2 and PySide2 from [here](https://download.qt.io/snapshots/ci/pyside/5.15/latest/pyside2/). You could also just wait for the official 5.15.3 release.

**Comment by JeremyStepp** [comment]
OneLauncher is now using PySide6 where this seems to not be an issue
