### ISSUE TITLE
Missing library on Arch

### ISSUE THREAD

**Issue by Madcliff** [JeremyStepp/OneLauncher#15]
I get the following error when I try to run the files installed by the .run file. 

ImportError: libssl.so.48: cannot open shared object file: No such file or directory

**Comment by JeremyStepp** [comment]
Could you try [this](https://www.swisstransfer.com/d/43abaf2b-722a-4824-b4c9-302158369e92) installer? I haven't done any testing yet, but the first thing that  comes to mind is that the current latest build was built with libressl rather than openssl.

**Comment by Madcliff** [comment]
Yeah that fixed the issue

**Comment by JeremyStepp** [comment]
Future builds should be fine then
