### ISSUE TITLE
Plugins missing from list or plugincompendium file detection sometimes fails

### ISSUE THREAD

**Issue by wduda** [JeremyStepp/OneLauncher#16]
Hi, I am on Windows10, OneLauncher v1.2.3, downloaded from GitHub.
Some plugins that have plugincompendium files like Voyage and Recipe Tracker V2 are showing up as Unmanaged.
I assume this is because they do not show up in the list of available plugins as well, on the Find More tab.

![image](https://user-images.githubusercontent.com/2854511/113864926-c7aae680-97ab-11eb-920f-f1d2420135e6.png)

**Comment by JeremyStepp** [comment]
It seems I missed Voyage and Recipe Tracker V2 in the RSS feed I track. They've been added now. You should also be able to reinstall any plugins without compendium files with OneLauncher and one will be generated.

**Comment by wduda** [comment]
Thanks for the update. But the behaviour has become somewhat weird now. Voyage is showing as installed when looking "Find more", but is missing from the installed list. The log stays completely empty.

![image](https://user-images.githubusercontent.com/2854511/114036399-538e4280-9880-11eb-9372-3927b233247d.png)
![image](https://user-images.githubusercontent.com/2854511/114036620-85070e00-9880-11eb-8602-fd7f5ed19ee2.png)
![image](https://user-images.githubusercontent.com/2854511/114036662-8e907600-9880-11eb-9d25-307da99a1461.png)
![image](https://user-images.githubusercontent.com/2854511/114036709-99e3a180-9880-11eb-9b1f-3c58729717a1.png)

I fixed that by restarting OneLauncher as admin (that did not help on its own), uninstalling and installing Voyage.

**Comment by wduda** [comment]
After that reinstall the issue was resolved.

**Comment by wduda** [comment]
Since the two plugins that were missing were added I will close the issue.
