### ISSUE TITLE
SSL error in HTTPS connection on Win10

### ISSUE THREAD

**Issue by wduda** [JeremyStepp/OneLauncher#17]
- OneLauncher cannot get news and world list, see screenshot below
- regular launcher connects fine
- installing/updating plugins with OneLauncher works fine so it can actually access the network
- OneLauncher is explicitly allowed in firewall

![image](https://user-images.githubusercontent.com/2854511/114672395-62a04500-9d05-11eb-85d9-e8fdf210ab64.png)

**Comment by JeremyStepp** [comment]
Can you upload your OneLauncher.log file that's in `<RootDrive>:\User\<LoggedInUser>\AppData\Roaming\OneLauncher` and tell me if you're using the latest OneLauncher release or the latest code from the git repository?

**Comment by wduda** [comment]
I am terribly sorry, I somehow missed notifications and emails about your question. For completeness sake, I was using the latest Windows release 1.2.3 from GitHub , and the log is attached.

Updating the ca_certs.pem with the version from GitHub has fixed the issue on Windows for me as well.

[OneLauncher.log](https://github.com/JeremyStepp/OneLauncher/files/6323906/OneLauncher.log)
