### ISSUE TITLE
LOTRO: Login to Treebeard and Shadowfax not working

### ISSUE THREAD

**Issue by wduda** [JeremyStepp/OneLauncher#21]
Logging in to the new legendary servers does not work. Also after the first unsuccessful login, all messages in log turn red afterwards if login is attempted again (see the account authenticated line).

![image](https://user-images.githubusercontent.com/2854511/124086327-3b7a2980-da51-11eb-9592-d0c6f418971f.png)

**Comment by JeremyStepp** [comment]
Fixed. For some reason, the status URLs for the legendary servers are different from the rest and always return "". I had to manually change the `URLs using Launcher.DataCenterService.GLS` from the game config.

**Comment by JeremyStepp** [comment]
I couldn't reproduce the rest of the text being red
