### ISSUE TITLE
Error logging into Treebeard

### ISSUE THREAD

**Issue by seanjorden** [JeremyStepp/OneLauncher#25]
Hi - I tried to login to Treebeard server and I get the following error message

[E10] Error getting world status. You may want to check the news feed for a scheduled down time.

Sequence of events
- Click Play
- Choose game account
- Click OK

The log looks like this

Initializing, please wait...
Available languages checked.
Fetched details from GLS data center.
World list obtained.
World queue configuration read.
Checking account details...
Account authenticated
[E10] Error getting world status. You may want to check the news feed for a scheduled down time.

Looks like a useful tool!

**Comment by JeremyStepp** [comment]
See #21. This is already fixed. Since the 2.0 release may take a while, I'll go ahead and do a new release from the stable branch that includes the fix for this.
