### ISSUE TITLE
Launcher not starting on MacOS Catalina

### ISSUE THREAD

**Issue by rfinkers** [JeremyStepp/OneLauncher#3]
QFSFileEngine::open: No file name specified - This error appears in the command line box.

In the graphic box:
Wanting to launch LOTR in 64bit mode. Launcher only shows abort button, launcher and save is greyed out. Last status message in the box is the mentioning of the game directory.

**Comment by JeremyStepp** [comment]
Unfortunately Apple removed support for 32-bit with the update to Catalina and that is currently required for WINE (used by mine and the official launcher for running the game on Mac) to function. It is hoped that this can be solved by the end of the year, but currently the only solution is downgrading or virtualization. This looks like possibly another error I will look into as well though based on your message. (As far as I know no one has tested OneLauncher on Mac yet, so there are probably a good few errors even on Mojave despite my best efforts at compatibility )

**Comment by rfinkers** [comment]
Thanks for the response, was hoping that your solution could bypass the 32-bit requirement of the official game launcher; as the game itself should already be 64-bit compatible. Keep on doing the good job.
